version: '2.4'
services:
    app:
      build: .
      depends_on:
        - postgres
          
    postgres:
      image: postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
